name: Greetings

on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  greeting:
    runs-on: ubuntu-latest
    name: First Comment
    permissions:
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Hola equipo!! Les deseo la mejor de las suertes en este sprint y en los próximos que vienen!! 🚀 '
