name: Greetings

on:
  pull_request:
    types: [opened]
    branches:
      - main
jobs:
  pr_check:
    runs-on: ubuntu-latest
    name: A job to Post comment on PR
    steps:
      - uses: actions/checkout@v2
      - name: PR Action
        uses: koushikmohan1996/action-pr-gifs@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: 'Hola equipo!! Les deseo la mejor de las suertes en este sprint y en los próximos que vienen!! 🚀 '
